### ISSUE TITLE
Support for IRIS Native API node.js

### ISSUE THREAD

**Issue by evshvarov** [chrisemunt/mg-dbx#2]
Could you please introduce the support for [Native API node.js](https://docs.intersystems.com/irislatest/csp/docbook/Doc.View.cls?KEY=PAGE_nodejs_native)

**Comment by chrisemunt** [comment]
mg-dbx actually replaces the functionality provided by "Native API Node.js".  The newer solution mg-dbx-napi is much faster than both mg-dbx and Native API Node.js.
